<a href="https://colab.research.google.com/github/Swetha0713/Generative-AI-2025/blob/main/2303A52415_33_8_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# -----------------------------------------------
# Wine Quality Prediction using ANN (Keras)
# Author: Ashutosh Kumar
# Date: 2025-02-23
# -----------------------------------------------

# STEP 1: IMPORT LIBRARIES
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

# STEP 2: LOAD DATASET
url = 'https://drive.google.com/uc?id=1uutPAkOSYb2Uror1mk2dZUtoYbCgz6DO'
df = pd.read_csv(url)

# STEP 3: PREPROCESSING
X = df.drop('quality', axis=1)
y = df['quality']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
y_encoded = to_categorical(y)

# STEP 4: SPLIT DATA
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

# STEP 5: BUILD MODEL
model = Sequential([
    Dense(16, input_dim=X.shape[1], activation='relu'),
    Dense(20, activation='relu'),
    Dense(25, activation='relu'),
    Dense(10, activation='relu'),
    Dense(y_encoded.shape[1], activation='softmax')
])
model.compile(optimizer='adadelta', loss='categorical_crossentropy', metrics=['accuracy'])

# STEP 6: TRAIN MODEL
history = model.fit(X_train, y_train, epochs=100, batch_size=64, validation_split=0.1)

# STEP 7: EVALUATE MODEL
train_loss, train_acc = model.evaluate(X_train, y_train, verbose=0)
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Training Accuracy: {train_acc:.4f}")
print(f"Testing Accuracy: {test_acc:.4f}")

# STEP 8: CONFUSION MATRIX AND METRICS
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

print("\nConfusion Matrix:")
print(confusion_matrix(y_true_classes, y_pred_classes))

print("\nClassification Report:")
print(classification_report(y_true_classes, y_pred_classes))

# STEP 9: SAVE MODEL
model.save("wine_ann_model.h5")
print("Model saved as wine_ann_model.h5")

# STEP 10: LOAD & USE MODEL
loaded_model = load_model("wine_ann_model.h5")
sample_input = X_test[0].reshape(1, -1)
sample_prediction = np.argmax(loaded_model.predict(sample_input))
print(f"\nPredicted Wine Quality for Sample: {sample_prediction}")


Epoch 1/100


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.1719 - loss: 2.1615 - val_accuracy: 0.1250 - val_loss: 2.1851
Epoch 2/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1863 - loss: 2.1566 - val_accuracy: 0.1250 - val_loss: 2.1848
Epoch 3/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1553 - loss: 2.1692 - val_accuracy: 0.1250 - val_loss: 2.1846
Epoch 4/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1730 - loss: 2.1670 - val_accuracy: 0.1250 - val_loss: 2.1843
Epoch 5/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1930 - loss: 2.1568 - val_accuracy: 0.1250 - val_loss: 2.1840
Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1779 - loss: 2.1531 - val_accuracy: 0.1250 - val_loss: 2.1837
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1676 - loss: 2.1736 - val_accuracy: 0.1250 - val_loss: 2.1835
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1896 - loss: 2.1581 - val_accuracy: 0.1250 - val_loss: 2.

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_


Confusion Matrix:
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 3  0  0  7  0  0  0]
 [63  0  0 67  0  0  0]
 [49  0  0 83  0  0  0]
 [15  0  0 27  0  0  0]
 [ 1  0  0  4  0  0  0]]

Classification Report:
              precision    recall  f1-score   support

           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        10
           5       0.35      0.52      0.42       130
           6       0.00      0.00      0.00       132
           7       0.00      0.00      0.00        42
           8       0.00      0.00      0.00         5

    accuracy                           0.21       320
   macro avg       0.05      0.07      0.06       320
weighted avg       0.14      0.21      0.17       320



Model saved as wine_ann_model.h5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step

Predicted Wine Quality for Sample: 5
