<a href="https://colab.research.google.com/github/Swetha0713/Generative-AI-2025/blob/main/generative_ai_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
y_actual = np.array([20, 30, 40, 50, 60])
y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])
mae = np.mean(np.abs(y_actual - y_pred))
mse = np.mean((y_actual - y_pred)**2)
rmse = np.sqrt(mse)


print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")


MAE: 0.4600000000000016
MSE: 0.24600000000000147
RMSE: 0.49598387070549127


USING LIBRARIES

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error

mae_lib = mean_absolute_error(y_actual, y_pred)
mse_lib = mean_squared_error(y_actual, y_pred)
rmse_lib = np.sqrt(mse_lib)
print(f"MAE (lib): {mae_lib}")
print(f"MSE (lib): {mse_lib}")
print(f"RMSE (lib): {rmse_lib}")


MAE (lib): 0.4600000000000016
MSE (lib): 0.24600000000000147
RMSE (lib): 0.49598387070549127


2 QUESTION

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_actual = np.array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
y_pred = np.array([0, 0, 0, 0, 0, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2])
conf_matrix = confusion_matrix(y_actual, y_pred)


accuracy = accuracy_score(y_actual, y_pred)
precision = precision_score(y_actual, y_pred, average='macro')
recall = recall_score(y_actual, y_pred, average='macro')
f1 = f1_score(y_actual, y_pred, average='macro')

print("Confusion Matrix:")
print(conf_matrix)
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")


Confusion Matrix:
[[2 1 2]
 [3 0 2]
 [2 1 2]]
Accuracy: 0.26666666666666666
Precision: 0.20634920634920637
Recall: 0.26666666666666666
F1 Score: 0.23232323232323235


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
conf_matrix_lib = confusion_matrix(y_actual, y_pred)
accuracy_lib = accuracy_score(y_actual, y_pred)
precision_lib = precision_score(y_actual, y_pred, average='macro')
recall_lib = recall_score(y_actual, y_pred, average='macro')
f1_lib = f1_score(y_actual, y_pred, average='macro')

print("Confusion Matrix (lib):")
print(conf_matrix_lib)
print(f"Accuracy (lib): {accuracy_lib}")
print(f"Precision (lib): {precision_lib}")
print(f"Recall (lib): {recall_lib}")
print(f"F1 Score (lib): {f1_lib}")


Confusion Matrix (lib):
[[2 1 2]
 [3 0 2]
 [2 1 2]]
Accuracy (lib): 0.26666666666666666
Precision (lib): 0.20634920634920637
Recall (lib): 0.26666666666666666
F1 Score (lib): 0.23232323232323235
